name: Sync submodules

on:
  schedule:
    - cron: "0 * * * *"   # every hour
  workflow_dispatch:       # allow manual trigger from GitHub UI

jobs:
  update-submodules:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout slipstream repo
        uses: actions/checkout@v3
        with:
          submodules: true
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Update submodules to latest main
        run: |
          git submodule update --remote --merge
          git add .
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git commit -m "Auto-update submodules" || echo "No changes"
          git push
